name: Matrix Demo
on: push
jobs: 
  build:
    strategy:
      matrix:
         # It will run for all combinaions of the values: version 12, 14, and 16 on both Windows and Ubuntu
        node-version: [12, 14, 16]
        operating-system: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.operating-system }} # It will run for all combinaions of the values
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }} # It will run for all combinaions of the values
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm build